steps:
  - name: "gcr.io/cloud-builders/go"
    args: ["install", "code"]
    env: ["GOPATH=./"]

  - name: "gcr.io/cloud-builders/go"
    args: ["test", "code"]
    env: ["GOPATH=./"]

    - id: "Building image from Dockerfile.prod"
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/devops_deploy:$SHORT_SHA', '-f', 'Dockerfile.prod', '.']

  - id: "Pushing image"
    name: "gcr.io/cloud-builders/docker"
    args: ['push', 'gcr.io/$PROJECT_ID/devops_deploy:$SHORT_SHA']

  - id: "Adjusting deployment file - K8S"
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      -  |
        sed 's#img-app-deployment#gcr.io/$PROJECT_ID/devops_deploy:$SHORT_SHA#g' k8s/go_deployment.yaml > k8s/go_deployment-new.yaml;
        cat k8s/go_deployment-new.yaml

  - id: "Deploy K8S"
    name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'k8s/go_deployment-new.yaml'
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'



